# https://github.com/go-task/task

version: '2'

tasks:
  dl-deps:
    desc: Downloads cli dependencies
    cmds:
      - go get -u github.com/golang/lint/golint

  lint:
    desc: Runs golint on this project
    cmds:
      - golint .

  test-sqlite:
    desc: Run tests for SQLite
    cmds:
      - task: test
        vars: {DATABASE: sqlite}

  test:
    cmds:
      - go test -v -tags {{.DATABASE}}
